[project]
name = "membase-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "membase>=0.1.7",
]

[tool.uv.sources]
membase = { git = "https://github.com/unibaseio/membase.git" }
